name: Origami
version: 1.0.0
date: 2020-05-11
description: |
    Computing Veech groups of origamis

authors:
    - name: Luca Junk
      url: http://www.math.uni-sb.de/ag/weitze/
    - name: Pascal Kattler
      url: http://www.math.uni-sb.de/ag/weitze/
    - name: Andrea Thevis
      url: http://www.math.uni-sb.de/ag/weitze/

maintainers:
    - name: Luca Junk
      url: http://www.math.uni-sb.de/ag/weitze/
    - name: Pascal Kattler
      url: http://www.math.uni-sb.de/ag/weitze/
    - name: Andrea Thevis
      url: http://www.math.uni-sb.de/ag/weitze/

GAP: "4.5.3"

needed-pkgs:
    - name: "ModularGroup"
      version: "1.0.0"
      url: "https://le-on.github.io/ModularGroup"
    - name: "Orb"
      version: "4.7.6"
      url: "https://gap-packages.github.io/orb"

suggested-pkgs:
    - name: "HomalgToCAS"
      version: "2018.06.15"
      url: "http://homalg-project.github.io/homalg_project/HomalgToCAS/"
    - name: "IO_ForHomalg"
      version: "2017.09.02"
      url: "http://homalg-project.github.io/homalg_project/IO_ForHomalg/"
    - name: "IO"
      version: "4.5.1"
      url: "https://gap-packages.github.io/io"
    - name: "RingsForHomalg"
      version: "2018.04.04"
      url: "http://homalg-project.github.io/homalg_project/RingsForHomalg/"
    - name: "ArangoDBInterface"
      version: "2019.07.30"
      url: "https://github.com/homalg-project/ArangoDBInterface/"

www: https://PascalKattler.github.io/Origami/
readme: README.md
packageinfo: https://PascalKattler.github.io/Origami/PackageInfo.g
github: https://github.com/PascalKattler/Origami

downloads:
    - name: .tar.gz
      url: https://github.com/PascalKattler/Origami/releases/download/v1.0.0/Origami-1.0.0.tar.gz
    - name: .zip
      url: https://github.com/PascalKattler/Origami/releases/download/v1.0.0/Origami-1.0.0.zip

abstract: |
    <span class="pkgname">Origami</span> is a package for computing the Veech group of square-tiled surfaces which are also known as origamis.

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/Origami.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>JKT20</span>]   <b class='BibAuthor'>Junk, L., Kattler, P. and Thevis, A.</b>,
     <i class='BibTitle'>Origami, Computing Veech groups of origamis,
             Version 1.0.0</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://PascalKattler.github.io/Origami/">https://PascalKattler.github.io/Origami/</a></span>.
    </p>
    

bibtex: |
    @misc{ Origami1.0.0,
      author =           {Junk, L. and Kattler, P. and Thevis, A.},
      title =            {{Origami},   Computing   Veech   groups  of  origamis,
                          {V}ersion 1.0.0},
      month =            {May},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href       {https://PascalKattler.github.io/Origami/}
                          {\texttt{https://PascalKattler.github.io/}\discretionary
                          {}{}{}\texttt{Origami/}}},
      printedkey =       {JKT20}
    }

